import "./bootstrap";
import * as SwalHelper from "./SwalHelper.js";
import "datatables.net-bs4";
import "datatables.net-buttons-bs4";
import "datatables.net-responsive-bs4";
import "datatables.net-bs4/css/dataTables.bootstrap4.min.css";
import "datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css";
import "datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css";
import { Html5Qrcode,Html5QrcodeScannerState } from "html5-qrcode";
import { MakeChart } from "./chart.js";
import Swal from "sweetalert2";
import { Jamhaha } from "./jam.js";
window.SwalHelper = SwalHelper;
window.MakeChart = MakeChart;
window.Swal = Swal;
window.Jamhaha = Jamhaha;
window.Html5Qrcode = Html5Qrcode;
window.Html5QrcodeScannerState = Html5QrcodeScannerState;
